### ISSUE TITLE
Cannot compile (link?) under arduino IDE

### ISSUE THREAD

**Issue by halicek** [lpodkalicki/attiny-tm1637-library#1]
Hi, trying to use your library in project on digispark (attiny85). But the example cannot be compiled.

The code (I have modified it for standard setup/loop but the original does the same:

> #include <stdint.h>
> #include <avr/io.h>
> #include <util/delay.h>
> #include <tm1637.h>
> uint8_t i = 0;
> 
> void setup() {
>   // put your setup code here, to run once:
> 
> TM1637_init();
> }
> 
> void loop() {
>   // put your main code here, to run repeatedly:
>     TM1637_display_digit(TM1637_SET_ADR_00H, i % 0x10);
>     TM1637_display_digit(TM1637_SET_ADR_01H, (i + 1) % 0x10);
>     TM1637_display_digit(TM1637_SET_ADR_02H, (i + 2) % 0x10);
>     TM1637_display_digit(TM1637_SET_ADR_03H, (i + 3) % 0x10);
>     TM1637_display_colon(true);
>     _delay_ms(200);
>     TM1637_display_colon(false);
>     _delay_ms(200);
>     i++;
> }

Results in:

> C:\Users\Josef\AppData\Local\Temp\arduino_build_886004\sketch\attiny85-display_4-7_test.ino.cpp.o: In function `setup':
> 
> D:\GDrive\Dokumenty\Arduino\attiny85-display_4-7_test/attiny85-display_4-7_test.ino:12: undefined reference to `TM1637_init()'
> 
> C:\Users\Josef\AppData\Local\Temp\arduino_build_886004\sketch\attiny85-display_4-7_test.ino.cpp.o: In function `loop':
> 
> D:\GDrive\Dokumenty\Arduino\attiny85-display_4-7_test/attiny85-display_4-7_test.ino:19: undefined reference to `TM1637_display_digit(unsigned char, unsigned char)'
> 
> D:\GDrive\Dokumenty\Arduino\attiny85-display_4-7_test/attiny85-display_4-7_test.ino:20: undefined reference to `TM1637_display_digit(unsigned char, unsigned char)'
> 
> D:\GDrive\Dokumenty\Arduino\attiny85-display_4-7_test/attiny85-display_4-7_test.ino:21: undefined reference to `TM1637_display_digit(unsigned char, unsigned char)'
> 
> D:\GDrive\Dokumenty\Arduino\attiny85-display_4-7_test/attiny85-display_4-7_test.ino:22: undefined reference to `TM1637_display_digit(unsigned char, unsigned char)'
> 
> D:\GDrive\Dokumenty\Arduino\attiny85-display_4-7_test/attiny85-display_4-7_test.ino:23: undefined reference to `TM1637_display_colon(bool)'
> 
> D:\GDrive\Dokumenty\Arduino\attiny85-display_4-7_test/attiny85-display_4-7_test.ino:25: undefined reference to `TM1637_display_colon(bool)'
> 
> collect2.exe: error: ld returned 1 exit status

This is on Arduino IDE 1.8.2.

What is strongly suspect is the order of linked files, because the build falls on:
Linking everything together...

> "C:\Users\Josef\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\4.8.1-arduino5/bin/avr-gcc" -Os -Wl,--gc-sections -mmcu=attiny85 -o "C:\Users\Josef\AppData\Local\Temp\arduino_build_886004/attiny85-display_4-7_test.ino.elf" "C:\Users\Josef\AppData\Local\Temp\arduino_build_886004\sketch\tm1637.c.o" "C:\Users\Josef\AppData\Local\Temp\arduino_build_886004\sketch\attiny85-display_4-7_test.ino.cpp.o" "C:\Users\Josef\AppData\Local\Temp\arduino_build_886004\libraries\attiny-tm1637\tm1637.c.o" "C:\Users\Josef\AppData\Local\Temp\arduino_build_886004\core\pins_arduino.c.o" "C:\Users\Josef\AppData\Local\Temp\arduino_cache_716708\core\core_digistump_avr_digispark-tiny_5a00834c4ebee8bef130e69d5b12399d.a" "-LC:\Users\Josef\AppData\Local\Temp\arduino_build_886004" -lm

**Comment by halicek** [comment]
When i write 

```
#include "tm1637.h"
#include "tm1637.c"
```

to the start of the sketch, the code compiles.

**Comment by lpodkalicki** [comment]
Hi, looks like you got problem with a linking C files. I really don't use Arduino to compile my sketches. Maybe try to change extension of source file to *.cpp ? Does it work properly when you include source file ?

**Comment by halicek** [comment]
Hi, yes, when directly linking the source files it works fine. I have ended switching to ssd1306-driven OLED.
